name: Build React Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: campus-connect-react/package-lock.json
    - run: npm ci
      working-directory: campus-connect-react
    - run: node --max-old-space-size=6000 $(which npm) run build
      working-directory: campus-connect-react
    - run: npm run test --if-present
      working-directory: campus-connect-react
